Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,7 +43,7 @@ jobs:
 
   build:
     runs-on: ubuntu-latest
-    needs: test  
+    needs: test
 
     steps:
       - name: Checkout code
@@ -55,26 +55,35 @@ jobs:
       - name: Build Streamlit Docker Image
         run: docker build -t xai-streamlit -f streamlit/Dockerfile .
 
-      - name: Start Docker Compose
+      - name: Start containers
         run: docker compose up -d
 
-      - name: Wait for API
+      - name: Wait for API to be ready
         run: |
-          sleep 20
-          curl --fail http://localhost:8000/ || exit 1
+          for i in {1..10}; do
+            if curl -s http://localhost:8000/ > /dev/null; then
+              echo "API is ready"
+              exit 0
+            fi
+            echo "Waiting for API..."
+            sleep 5
+          done
+          echo "API failed to start"
+          exit 1
 
       - name: Stop containers
         run: docker compose down
 
+
   push:
     runs-on: ubuntu-latest
-    needs: build 
+    needs: build
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Build images again (required in new runner)
+      - name: Build images again
         run: |
           docker build -t xai-api -f app/Dockerfile .
           docker build -t xai-streamlit -f streamlit/Dockerfile .
